Update bootstrap.php
Boa Tarde

Criei uma pasta /test

Criei um arquivo composer.json com o seguinte conteudo

	{
	   "minimum-stability": "dev",
	   "prefer-stable": true,
	   "require": {
	      "lucasmro/clearsale": "*"
	   }
	}

No terminal executei o comando

	composer install

Foi feito os devidos downloads

Acessei

http://127.0.0.1/public_html/test/vendor/nfephp-org/nfephp/install/

e foi exibido o erro


	Warning: include(/home/marcio/dados/public_html/test/vendor/nfephp-org/nfephp/vendor/autoload.php): failed to open stream: No such file or directory in /home/marcio/dados/public_html/test/vendor/nfephp-org/nfephp/bootstrap.php on line 3

	Warning: include(): Failed opening '/home/marcio/dados/public_html/test/vendor/nfephp-org/nfephp/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /home/marcio/dados/public_html/test/vendor/nfephp-org/nfephp/bootstrap.php on line 3

	Fatal error: Uncaught Error: Class 'NFePHP\Common\Configure\Configure' not found in /home/marcio/dados/public_html/test/vendor/nfephp-org/nfephp/install/index.php:47 Stack trace: #0 {main} thrown in /home/marcio/dados/public_html/test/vendor/nfephp-org/nfephp/install/index.php on line 47


Editei o arquivo

/home/marcio/dados/public_html/test/vendor/nfephp-org/nfephp/bootstrap.php

alterando o trecho

DE

	include __DIR__ . '/vendor/autoload.php';

PARA

	$depth = 2;
	$path = dirname(__FILE__);
	for( $d=1 ; $d <= $depth ; $d++ ) {
	    $path = dirname($path);
	}
	$vendorDir = $path;

	$autoload_path = $vendorDir . '/autoload.php';

	$included = include $autoload_path;

	if (!$included) {
	    echo 'Falha no carregamento do autoload';
	    exit(1);
	}

Agora funcionou o apontamento para o autoload

Veja os passos a passo conforme imagens

http://pasteboard.co/18JW1l5l.png

http://pasteboard.co/18JXdhX6.png

http://pasteboard.co/18JYvL3q.png

http://pasteboard.co/18K02tAv.png